version: '3'
services:
  webapp:
    image: rachaz/runninghi-dev
    restart: always
    container_name: runninghi_spring_boot_dev
    expose:
      - "8081"
    ports: # host - container 포트 매핑
      - "8081:8081"