spring:
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          #          naver:
          #            client-id: xxx
          #            client-secret: xxx
          #            scope:
          #              - name
          #              - email
          #            #- profile_image
          #            client-name: Naver
          #            authorization-grant-type: authorization_code
          #            redirect-uri: http://localhost:8880/login/oauth2/code/naver

          kakao:
            client-id: 9a41e071dfbe8d7a22335b8e260dc8e8
            client-secret: NG0BUacgojEc914cdgCA5DdIlX3BQMSZ
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8880/login/oauth2/code/kakao #?? ??? ?? uri


        provider: #???? provider? ???? ?? ?? ???? ??????.
          #          naver:
          #            authorization-uri: https://nid.naver.com/oauth2.0/authorize #??? ??? ?? ??? ??
          #            token-uri: https://nid.naver.com/oauth2.0/token #??? ?? uri
          #            user-info-uri: https://openapi.naver.com/v1/nid/me #??? ??? ?? uri
          #            user-name-attribute: response #?? ??? json ??? ??? response ?? ???? ???? ????

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

          # ??? OAuth2-client ?????? provider ?? ??,????,???? ???? redirect-uri , authorization-grant-type ? ???? ??? ???? ????? ???? ??.(???? ??.) ex) /login/oauth2/facebook, google ? ??
          # ??? ???? ????? Provider ? ??? ??? ???????. ????? uri ? ???? ??, ???? ?? ??.