spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runninghi?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: runninghi
    password: runninghi
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
