spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runninghi?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: runninghi
    password: runninghi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none
      # 개발 초기 단계 또는 로컬에서 테스트 : create 또는 update
      # 테스트 서버 : update 또는 validate
      # 스테이징 및 운영 서버 : validate 또는 none
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          #          naver:
          #            client-id: xxx
          #            client-secret: xxx
          #            scope:
          #              - name
          #              - email
          #            #- profile_image
          #            client-name: Naver
          #            authorization-grant-type: authorization_code
          #            redirect-uri: http://localhost:8880/login/oauth2/code/naver

          kakao:
            client-id: 9a41e071dfbe8d7a22335b8e260dc8e8
            client-secret: NG0BUacgojEc914cdgCA5DdIlX3BQMSZ
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            redirect-uri: http://localhost:8880/login/oauth2/code/kakao # 리다이렉트 uri
            authorization-grant-type: authorization_code
            client-authentication-method: POST


        provider: #???? provider? ???? ?? ?? ???? ??????.
          #          naver:
          #            authorization-uri: https://nid.naver.com/oauth2.0/authorize #??? ??? ?? ??? ??
          #            token-uri: https://nid.naver.com/oauth2.0/token #??? ?? uri
          #            user-info-uri: https://openapi.naver.com/v1/nid/me #??? ??? ?? uri
          #            user-name-attribute: response #?? ??? json ??? ??? response ?? ???? ???? ????

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

          # ??? OAuth2-client ?????? provider ?? ??,????,???? ???? redirect-uri , authorization-grant-type ? ???? ??? ???? ????? ???? ??.(???? ??.) ex) /login/oauth2/facebook, google ? ??
          # ??? ???? ????? Provider ? ??? ??? ???????. ????? uri ? ???? ??, ???? ?? ??.