server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  cloud:
    config:
      import: "optional:configserver: http://localhost:8888"
  profiles:
    #운영환경 or 로컬 환경 중에 선택
    #로컬 = dev, 운영 = prod
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      auto-commit: true


  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      # activate가 dev일때만, create, create-drop
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/data/data.sql
      # activate가 dev일때만 always / prod일때는 never
      mode: always
      platform: mysql
      encoding: UTF-8

  security:
    user:
      password: 1
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9a41e071dfbe8d7a22335b8e260dc8e8
            client-secret: NG0BUacgojEc914cdgCA5DdIlX3BQMSZ
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao # 리다이렉트 uri
            authorization-grant-type: authorization_code
            client-authentication-method: POST


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        springdoc:
          default-consumes-media-type: application/json;charset=UTF-8
          default-produces-media-type: application/json;charset=UTF-8
          paths-to-match: /**
          swagger-ui:
            path: /
            display-request-duration: true
            groups-order: desc
            operations-sorter: alpha
            disable-swagger-default-url: true
          api-docs:
            groups:
              enabled: true