server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    #운영환경 or 로컬 환경 중에 선택
    #로컬 = dev, 운영 = prod
    active: dev


  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl : true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      # activate가 dev일때만, create, create-drop
      ddl-auto: create-drop
    #      use-new-id-generator-mappings: false
    defer-datasource-initialization : true
  sql:
    init:
      data-locations: classpath:db/data/data.sql
      # activate가 dev일때만 always / prod일때는 never
      mode: always
      platform: mysql
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          #          naver:
          #            client-id: xxx
          #            client-secret: xxx
          #            scope:
          #              - name
          #              - email
          #            #- profile_image
          #            client-name: Naver
          #            authorization-grant-type: authorization_code
          #            redirect-uri: http://localhost:8880/login/oauth2/code/naver

          kakao:
            client-id: 9a41e071dfbe8d7a22335b8e260dc8e8
            client-secret: NG0BUacgojEc914cdgCA5DdIlX3BQMSZ
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao # \uB9AC\uB2E4\uC774\uB809\uD2B8 uri
            authorization-grant-type: authorization_code
            client-authentication-method: POST


        provider: #\uB124\uC774\uBC84, \uCE74\uCE74\uC624\uC758 provider\uB294 \uB4F1\uB85D\uB418\uC5B4 \uC788\uC9C0 \uC54A\uC544 \uC0AC\uC6A9\uC790\uAC00 \uB4F1\uB85D\uD574\uC57C\uB41C\uB2E4.
          #          naver:
          #            authorization-uri: https://nid.naver.com/oauth2.0/authorize #\uB124\uC774\uBC84 \uB85C\uADF8\uC778 \uCC3D\uC744 \uBC1B\uC744\uC218 \uC788\uB2E4
          #            token-uri: https://nid.naver.com/oauth2.0/token #\uD1A0\uD070\uC744 \uBC1B\uB294 uri
          #            user-info-uri: https://openapi.naver.com/v1/nid/me #\uD504\uB85C\uD544 \uC8FC\uC18C\uB97C \uBC1B\uB294 uri
          #            user-name-attribute: response #\uD68C\uC6D0 \uC815\uBCF4\uB97C json \uD615\uD0DC\uB85C \uBC1B\uB294\uB370 response \uB77C\uB294 \uD0A4\uAC12\uC73C\uB85C \uB124\uC774\uBC84\uAC00 \uB9AC\uD134\uD574\uC90C

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

            # \uC2A4\uD504\uB9C1 OAuth2-client \uB77C\uC774\uBE0C\uB7EC\uB9AC\uC758 provider \uC5D0\uB294 \uAD6C\uAE00,\uD398\uC774\uC2A4\uBD81,\uD2B8\uC704\uD130\uAC00 \uC18D\uD574\uC788\uC5B4 redirect-uri , authorization-grant-type \uB97C \uC801\uC5B4\uC8FC\uC9C0 \uC54A\uC544\uB3C4 \uC790\uB3D9\uC73C\uB85C \uACE0\uC815\uC801\uC73C\uB85C \uB4F1\uB85D\uB418\uC5B4 \uC788\uB2E4.(\uC801\uC5B4\uC918\uB3C4 \uB41C\uB2E4.) ex) /login/oauth2/facebook, google \uB85C \uACE0\uC815
            # \uD558\uC9C0\uB9CC \uB124\uC774\uBC84\uB098 \uCE74\uCE74\uC624\uD1A1\uC740 Provider \uAC00 \uC544\uB2C8\uAE30 \uB54C\uBB38\uC5D0 \uC801\uC5B4\uC8FC\uC5B4\uC57C\uB41C\uB2E4. \uC6D0\uD558\uB294\uB300\uB85C uri \uB97C \uC9C0\uC815\uD560\uC218 \uC788\uB2E4, \uACE0\uC815\uB418\uC5B4 \uC788\uC9C0 \uC54A\uB2E4.