name: Java CI with Gradle

on:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:

  cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cloud Config Server
        uses: actions/checkout@v3
        with:
          repository: cca-ffodregamdi/running-hi-cloud-server
          token: ${{ secrets.GH_PAT }}
          ref: master

      - name: Set up JDK 17 in Cloud Config Server
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Cloud Config Server
        run: |
          chmod +x gradlew
          ./gradlew clean build
          ls ./build/libs

      - name: Run Spring Cloud Config Server
        run: |
          chmod +x ./build/libs/running-hi-cloud-server-0.0.1-SNAPSHOT.jar
          java -jar ./build/libs/running-hi-cloud-server-0.0.1-SNAPSHOT.jar

      - name: Wait for client to complete
        run: sleep 180

      - name: Stop running Spring Cloud Config Server
        run: |
          pkill -f "java -jar ./build/libs/running-hi-cloud-server-0.0.1-SNAPSHOT.jar"


  client:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: cca-ffodregamdi/running-hi-back

      - name: Wait for cloud to run
        run: sleep 60

      - name: Set up JDK 17 in Client
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql database: 'runninghi'
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Build and Test with Gradle
        run: |
          chmod +x gradlew
          ls ./gradlew
          ./gradlew --info test

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: running-hi-cloud-client/build/test-results/test/**/*.xml