name: Java CI with Gradle

on:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:
  cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cloud Config Server
        uses: actions/checkout@v2
        with:
          repository: cca-ffodregamdi/running-hi-cloud-server
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Set up JDK 17 in Cloud Config Server
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Spring Cloud Config Server
        run: |
          cd running-hi-cloud-server
          ./gradlew clean build
        working-directory: running-hi-cloud-server

      - name: Run Spring Cloud Config Server
        run: java -jar running-hi-cloud-server/build/libs/running-hi-cloud-server.jar
        working-directory: running-hi-cloud-server

  client:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17 in Client
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql-database: 'runninghi'
          mysql-user: ${{ secrets.MYSQL_USERNAME }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Checkout Cloud Config Client
        uses: actions/checkout@v2
        with:
          repository: cca-ffodregamdi/running-hi-cloud-client
          token: ${{ secrets.GH_PAT }}
          ref: dev

      - name: Build and Test with Gradle
        run: |
          cd running-hi-cloud-client
          chmod +x gradlew
          ./gradlew --info test
        working-directory: running-hi-cloud-client

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: running-hi-cloud-client/build/test-results/test/**/*.xml
