name: Java CI with Gradle

# dev 브랜치에 pr 시 actions 실행
on:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:
  # ! application server
  client:
    runs-on: ubuntu-latest

    steps:

      # cloud config server가 실행될 때까지 60초 기다림
      - name: Wait for cloud to run
        run: sleep 60

      # jdk 설정
      - name: Set up JDK 17 in Client
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # mysql 설정
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql database: 'runninghi'
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: make application.yml
        run:
          touch ./src/main/resources/application.yml
        shell: bash

      - name: deliver application.yml
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        shell: bash

      # test 실행
      - name: Build and Test with Gradle
        run: |
          chmod +x gradlew
          ls ./gradlew
          ./gradlew --info test

      # build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      # test 결과 출력
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: build/test-results/test/**/*.xml